// <auto-generated />
using System;
using HomeRadar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeRadar.Migrations
{
    [DbContext(typeof(EmlakContext))]
    partial class EmlakContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeRadar.Models.BuildingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BuildingTypes");
                });

            modelBuilder.Entity("HomeRadar.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("City");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("HomeRadar.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Features");
                });

            modelBuilder.Entity("HomeRadar.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Aidat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("Aidat");

                    b.Property<int?>("BathroomCount")
                        .HasColumnType("integer")
                        .HasColumnName("BathroomCount");

                    b.Property<int>("BuildingAge")
                        .HasColumnType("integer")
                        .HasColumnName("BuildingAge");

                    b.Property<string>("BuildingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("BuildingStatus");

                    b.Property<int>("BuildingTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("BuildingTypeId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DeedStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("DeedStatus");

                    b.Property<string>("Direction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Direction");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("DistrictId");

                    b.Property<string>("Floor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Floor");

                    b.Property<string>("FurnitureStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FurnitureStatus");

                    b.Property<bool?>("HasBalcony")
                        .HasColumnType("boolean")
                        .HasColumnName("HasBalcony");

                    b.Property<bool?>("HasElevator")
                        .HasColumnType("boolean")
                        .HasColumnName("HasElevator");

                    b.Property<bool?>("HasGarage")
                        .HasColumnType("boolean")
                        .HasColumnName("HasGarage");

                    b.Property<bool?>("HasSecurity")
                        .HasColumnType("boolean")
                        .HasColumnName("HasSecurity");

                    b.Property<string>("HeatingType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("HeatingType");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<bool?>("IsCreditSuitable")
                        .HasColumnType("boolean")
                        .HasColumnName("IsCreditSuitable");

                    b.Property<bool?>("IsExchangeable")
                        .HasColumnType("boolean")
                        .HasColumnName("IsExchangeable");

                    b.Property<bool?>("IsInComplex")
                        .HasColumnType("boolean")
                        .HasColumnName("IsInComplex");

                    b.Property<DateTime>("ListingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ListingDate");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Neighborhood");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<int>("RoomCount")
                        .HasColumnType("integer")
                        .HasColumnName("RoomCount");

                    b.Property<int>("SalonCount")
                        .HasColumnType("integer")
                        .HasColumnName("SalonCount");

                    b.Property<decimal>("SquareMeters")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("SquareMeters");

                    b.Property<string>("UsageStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("UsageStatus");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("HomeRadar.Models.ListingFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer")
                        .HasColumnName("FeatureId");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer")
                        .HasColumnName("ListingId");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("ListingId", "FeatureId")
                        .IsUnique();

                    b.ToTable("ListingFeatures");
                });

            modelBuilder.Entity("HomeRadar.Models.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingAge")
                        .HasColumnType("integer")
                        .HasColumnName("BuildingAge");

                    b.Property<int?>("BuildingTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("BuildingTypeId");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ConfidenceScore");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("DistrictId");

                    b.Property<int?>("ListingId")
                        .HasColumnType("integer")
                        .HasColumnName("ListingId");

                    b.Property<string>("ModelName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ModelName");

                    b.Property<decimal>("PredictedPriceAvg")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PredictedPriceAvg");

                    b.Property<decimal>("PredictedPriceMax")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PredictedPriceMax");

                    b.Property<decimal>("PredictedPriceMin")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PredictedPriceMin");

                    b.Property<int>("RoomCount")
                        .HasColumnType("integer")
                        .HasColumnName("RoomCount");

                    b.Property<decimal>("SquareMeters")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("SquareMeters");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("HomeRadar.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LastName");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeRadar.Models.Listing", b =>
                {
                    b.HasOne("HomeRadar.Models.BuildingType", "BuildingType")
                        .WithMany("Listings")
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeRadar.Models.District", "District")
                        .WithMany("Listings")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuildingType");

                    b.Navigation("District");
                });

            modelBuilder.Entity("HomeRadar.Models.ListingFeature", b =>
                {
                    b.HasOne("HomeRadar.Models.Feature", "Feature")
                        .WithMany("ListingFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeRadar.Models.Listing", "Listing")
                        .WithMany("ListingFeatures")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("HomeRadar.Models.Prediction", b =>
                {
                    b.HasOne("HomeRadar.Models.BuildingType", "BuildingType")
                        .WithMany()
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HomeRadar.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeRadar.Models.Listing", "Listing")
                        .WithMany("Predictions")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HomeRadar.Models.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BuildingType");

                    b.Navigation("District");

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeRadar.Models.BuildingType", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("HomeRadar.Models.District", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("HomeRadar.Models.Feature", b =>
                {
                    b.Navigation("ListingFeatures");
                });

            modelBuilder.Entity("HomeRadar.Models.Listing", b =>
                {
                    b.Navigation("ListingFeatures");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("HomeRadar.Models.User", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
