// <auto-generated />
using System;
using HomeRadar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HomeRadar.Migrations
{
    [DbContext(typeof(EmlakContext))]
    [Migration("20251215112532_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HomeRadar.Models.BuildingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BuildingTypes");
                });

            modelBuilder.Entity("HomeRadar.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("City")
                        .HasColumnName("City")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("HomeRadar.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnName("Description")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Features");
                });

            modelBuilder.Entity("HomeRadar.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal?>("Aidat")
                        .HasColumnName("Aidat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("BathroomCount")
                        .HasColumnName("BathroomCount")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingAge")
                        .HasColumnName("BuildingAge")
                        .HasColumnType("integer");

                    b.Property<string>("BuildingStatus")
                        .HasColumnName("BuildingStatus")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("BuildingTypeId")
                        .HasColumnName("BuildingTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeedStatus")
                        .HasColumnName("DeedStatus")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Direction")
                        .HasColumnName("Direction")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("DistrictId")
                        .HasColumnName("DistrictId")
                        .HasColumnType("integer");

                    b.Property<string>("Floor")
                        .HasColumnName("Floor")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FurnitureStatus")
                        .HasColumnName("FurnitureStatus")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("HasBalcony")
                        .HasColumnName("HasBalcony")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasElevator")
                        .HasColumnName("HasElevator")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGarage")
                        .HasColumnName("HasGarage")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasSecurity")
                        .HasColumnName("HasSecurity")
                        .HasColumnType("boolean");

                    b.Property<string>("HeatingType")
                        .HasColumnName("HeatingType")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsCreditSuitable")
                        .HasColumnName("IsCreditSuitable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsExchangeable")
                        .HasColumnName("IsExchangeable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsInComplex")
                        .HasColumnName("IsInComplex")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ListingDate")
                        .HasColumnName("ListingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Neighborhood")
                        .HasColumnName("Neighborhood")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomCount")
                        .HasColumnName("RoomCount")
                        .HasColumnType("integer");

                    b.Property<int>("SalonCount")
                        .HasColumnName("SalonCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("SquareMeters")
                        .HasColumnName("SquareMeters")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UsageStatus")
                        .HasColumnName("UsageStatus")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("HomeRadar.Models.ListingFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FeatureId")
                        .HasColumnName("FeatureId")
                        .HasColumnType("integer");

                    b.Property<int>("ListingId")
                        .HasColumnName("ListingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("ListingId", "FeatureId")
                        .IsUnique();

                    b.ToTable("ListingFeatures");
                });

            modelBuilder.Entity("HomeRadar.Models.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BuildingAge")
                        .HasColumnName("BuildingAge")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingTypeId")
                        .HasColumnName("BuildingTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnName("ConfidenceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DistrictId")
                        .HasColumnName("DistrictId")
                        .HasColumnType("integer");

                    b.Property<int?>("ListingId")
                        .HasColumnName("ListingId")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .HasColumnName("ModelName")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("PredictedPriceAvg")
                        .HasColumnName("PredictedPriceAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PredictedPriceMax")
                        .HasColumnName("PredictedPriceMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PredictedPriceMin")
                        .HasColumnName("PredictedPriceMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomCount")
                        .HasColumnName("RoomCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("SquareMeters")
                        .HasColumnName("SquareMeters")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("HomeRadar.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("FirstName")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnName("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("LastName")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnName("PasswordHash")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnName("Role")
                        .HasColumnType("character varying(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeRadar.Models.Listing", b =>
                {
                    b.HasOne("HomeRadar.Models.BuildingType", "BuildingType")
                        .WithMany("Listings")
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeRadar.Models.District", "District")
                        .WithMany("Listings")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeRadar.Models.ListingFeature", b =>
                {
                    b.HasOne("HomeRadar.Models.Feature", "Feature")
                        .WithMany("ListingFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeRadar.Models.Listing", "Listing")
                        .WithMany("ListingFeatures")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeRadar.Models.Prediction", b =>
                {
                    b.HasOne("HomeRadar.Models.BuildingType", "BuildingType")
                        .WithMany()
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HomeRadar.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HomeRadar.Models.Listing", "Listing")
                        .WithMany("Predictions")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HomeRadar.Models.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
